* License

  All of Labdoo's source code is released under GPL version 3 or later.

* Installation

  The recommended way of installation is to build a new server from
  scratch, inside a chroot environment.

  + Get a copy of the project from GitHub:
    #+BEGIN_EXAMPLE
    mkdir /var/chroot
    cd /var/chroot/
    git clone https://github.com/Labdoo/Labdoo-2.0.git labdoo
    #+END_EXAMPLE

  + If you intend to build the master branch, skip the following step:
    #+BEGIN_EXAMPLE
    cd labdoo/
    git checkout $NAME_OF_THE_BRANCH
    cd ../
    #+END_EXAMPLE

  + Modify and customize the settings:
    #+BEGIN_EXAMPLE
    cp labdoo/install/settings.sh labdoo/cfg.sh
    vim labdoo/cfg.sh # Make any necessary changes
    #+END_EXAMPLE

  + Install the project inside a chroot system:
    #+BEGIN_EXAMPLE
    time nohup nice labdoo/install/chroot.sh labdoo/cfg.sh &
    tail -f nohup.out
    less -r nohup.out
    #+END_EXAMPLE

    The above process can take some time, depending on bandwidth and your computer speed.
    On an Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz with 1GB of RAM it takes 9 minutes and 41 seconds:

    #+BEGIN_EXAMPLE
    real 9m41.223s
    user 3m38.554s
    sys 0m36.375s 
    #+END_EXAMPLE

  + Make sure to include the following lines in your /etc/hosts file (outside the chroot):

    #+BEGIN_EXAMPLE
    127.0.0.1       www.labdoo-dev.org localhost
    #+END_EXAMPLE

  + Start the Labdoo social network: 
    #+BEGIN_EXAMPLE
    service chroot-lbd start
    #+END_EXAMPLE

  + And that's it! You can now access your Labdoo installation
    by opening your web browser and opening the URL https://www.labdoo-dev.org/. Please use https
    protocol (instead of http) since currently the theme only works properly on https. (Notice
    that you will need to confirm the security exception on your browser the first time you
    access https://www.labdoo-dev.org/)

  + If you need to stop Labdoo you can do: =service chroot-lbd stop=
  
  + If you need to start again Labdoo you can do: =service chroot-lbd start=

* Installation in a docker container

  This is almost the same as the installation above, except that instead of ~install/chroot.sh~
  you call ~install/docker.sh~:
  #+BEGIN_EXAMPLE
  nohup time nice labdoo/install/docker.sh labdoo/cfg.sh &
  #+END_EXAMPLE

  Then to stop and start Labdoo you do: =docker.io stop lbd= and =docker.io start lbd=.


** Building with docker

   Another way is to use the command =docker build= to build an image
   and then =docker run= to create a container from this image:
   #+BEGIN_EXAMPLE
   vim labdoo/install/settings.sh
   docker.io build --tag=labdoo labdoo/
   docker.io run -d --name=lbd --hostname=example.org -p 80:80 -p 443:443 labdoo
   #+END_EXAMPLE

* Documentation

  - Internal doc files:
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/README.org][README.org]] (this file)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/dev/README.org][dev/README.org]] (tips for developers)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/modules/features/README.org][modules/features/README.org]]

  - Other docs that may be useful:
    + http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/
    + http://dashohoxha.blogspot.com/2012/08/how-to-secure-ubuntu-server.html
    + http://dashohoxha.blogspot.com/2013/07/how-to-manage-your-own-domain-name.html
    + http://dashohoxha.blogspot.com/2013/02/how-to-set-up-chroot-environment-for.html
    + http://dashohoxha.blogspot.com/2012/10/using-nginx-as-web-server-for-drupal.html
    + http://www.havetheknowhow.com/Configure-the-server/Install-ssmtp.html
    + http://arstechnica.com/security/2009/12/how-to-get-set-with-a-secure-sertificate-for-free/
    + http://academia.edu/3993827/Development_Setup_Of_B-Translator
