* License

  All of Labdoo's source code is released under GPL version 3 or later.

* Installation

  The recommended way of installation is to build a new server from
  scratch, inside a chroot environment.

  + Get a copy of the project from GitHub:
    #+BEGIN_EXAMPLE
    mkdir /var/chroot
    cd /var/chroot/
    git clone https://github.com/Labdoo/Labdoo-2.0.git labdoo
    #+END_EXAMPLE

  + Modify and customize the settings:
    #+BEGIN_EXAMPLE
    cp labdoo/install/settings.sh labdoo/cfg.sh
    vim labdoo/cfg.sh # Make any necessary changes
    #+END_EXAMPLE

  + Install the project inside a chroot system:
    #+BEGIN_EXAMPLE
    time nohup nice labdoo/install/chroot.sh labdoo/cfg.sh &
    tail -f nohup.out
    less -r nohup.out
    #+END_EXAMPLE

    The above process can take a few tens of minutes, depending on bandwidth and your computer speed.

  + Make sure to include the following lines in your /etc/hosts file (outside the chroot):

    #+BEGIN_EXAMPLE
    127.0.0.1       www.labdoo-dev.org localhost
    #+END_EXAMPLE

  + Start the Labdoo social network: 
    #+BEGIN_EXAMPLE
    service chroot-lbd start
    #+END_EXAMPLE

  + And that's it! You can now access your Labdoo installation
    by opening your web browser and opening the URL https://www.labdoo-dev.org/. Please use https
    protocol (instead of http) since currently the theme only works properly on https. (Notice
    that you will need to confirm the security exception on your browser the first time you
    access https://www.labdoo-dev.org/)

  + If you need to stop Labdoo you can do: =service chroot-lbd stop=
  
  + If you need to start again Labdoo you can do: =service chroot-lbd start=

* Documentation

  - Internal doc files:
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/README.org][README.org]] (this file)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/dev/README.org][dev/README.org]] (tips for developers)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/modules/features/README.org][modules/features/README.org]]

  - Other docs that may be useful:
    + http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/
    + http://dashohoxha.blogspot.com/2012/08/how-to-secure-ubuntu-server.html
    + http://dashohoxha.blogspot.com/2013/07/how-to-manage-your-own-domain-name.html
    + http://dashohoxha.blogspot.com/2013/02/how-to-set-up-chroot-environment-for.html
    + http://dashohoxha.blogspot.com/2012/10/using-nginx-as-web-server-for-drupal.html
    + http://www.havetheknowhow.com/Configure-the-server/Install-ssmtp.html
    + http://arstechnica.com/security/2009/12/how-to-get-set-with-a-secure-sertificate-for-free/
    + http://academia.edu/3993827/Development_Setup_Of_B-Translator
