* License

  All of Labdoo's source code is released under GPL version 3 or later.

* Installation

  The recommended way of installation is to build a new server from
  scratch, inside a chroot environment.

  + Get a copy of the project from GitHub:
    #+BEGIN_EXAMPLE
    mkdir /var/chroot
    cd /var/chroot/
    git clone https://github.com/Labdoo/Labdoo-2.0.git Labdoo
    #+END_EXAMPLE

  + Install Labdoo inside a chroot system:
    #+BEGIN_EXAMPLE
    nohup nice Labdoo/install/install.sh lbd &
    tail -f nohup.out
    #+END_EXAMPLE

  + Configure it (See next section for sample values when running the following command): 
    #+BEGIN_EXAMPLE
    chroot lbd/ /tmp/install/config.sh 
    #+END_EXAMPLE

  + And that's it! you are now ready to open your browser and access your local Labdoo installation. 
  
  + If you need to stop Labdoo you can do: =service chroot-lbd stop=
  
  + If you need to start Labdoo you can do: =service chroot-lbd start=

* Configuration parameters 

  When running the command =chroot lbd/ /tmp/install/config.sh=, you will be asked
  to enter several configuration parameters. You can choose your options here,
  but here are the recommended values to enter if you are a Labdoo developer.

    #+BEGIN_EXAMPLE
    Enter the domain [www.labdoo-dev.org]: 
    [press ENTER here to select the default]
    Enter root password [89a67fb3a0]: 
    [use a simple password, for instance, "grassroots"]
    Please enter new password for the MySQL 'lbd' account.
    Enter password [057e80488289da38]: 
    [use a simple password, for instance, "grassroots"]
    Enter the gmail address [MyEmailAddress@gmail.com]: 
    [enter "dev-user@labdoo.org"]
    Enter the gmail password: 
    [you need to enter "grassroots" here]
    Please enter the email address of the 'admin' user account in Drupal: 
    [enter "dev-user@labdoo.org"]
    Please enter new password for the 'admin' user account in Drupal.
    Enter the password: [enter "grassroots" here]
    #+END_EXAMPLE

  dev-user@labdoo.org is a special Labdoo email account used for development. You can access
  this account by going to the Labdoo email URL mail.labdoo.org and use the password "grassroots".

  Finally, make sure to include the following lines in your /etc/hosts file (outside the chroot):

    #+BEGIN_EXAMPLE
    127.0.0.1       www.labdoo-dev.org localhost
    #+END_EXAMPLE

  After using the above configuration parameters, you can now access your Labdoo installation
  by opening your web browser and opening the URL https://www.labdoo-dev.org/. Please use https
  protocol (instead of http) since currently the theme only works properly on https. (Notice
  that you will need to confirm the security exception on your browser the first time you
  access https://www.labdoo-dev.org/)

* Documentation

  - Internal doc files:
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/README.org][README.org]] (this file)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/dev/README.org][dev/README.org]] (tips for developers)
    + [[https://github.com/Labdoo/Labdoo-2.0/blob/master/modules/features/README.org][modules/features/README.org]]

  - Other docs that may be useful:
    + http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/
    + http://dashohoxha.blogspot.com/2012/08/how-to-secure-ubuntu-server.html
    + http://dashohoxha.blogspot.com/2013/07/how-to-manage-your-own-domain-name.html
    + http://dashohoxha.blogspot.com/2013/02/how-to-set-up-chroot-environment-for.html
    + http://dashohoxha.blogspot.com/2012/10/using-nginx-as-web-server-for-drupal.html
    + http://www.havetheknowhow.com/Configure-the-server/Install-ssmtp.html
    + http://arstechnica.com/security/2009/12/how-to-get-set-with-a-secure-sertificate-for-free/
    + http://academia.edu/3993827/Development_Setup_Of_B-Translator
