<?php

/**
 * @defgroup labdoowiki LabdooWiki: Module implementing Labdoo's wiki-type documentation system
 *
 * Implements supporting features for Labdoo's wiki. 
 *
 */


/**
 * @file
 * Main module file for the Labdoo Wiki 
 *
 * @ingroup labdoowiki
 *
 */


/**
 * Implementation of hook_views_api
 */
function lbd_wiki_views_api() {
  return array(
    'api' => 3.0,
  );
} 


/**
 * Implementation of hook_views_default_views
 */
function lbd_wiki_views_default_views() {

  // Teams view
  include 'lbd_wiki_views_books_list.inc';
  $views[$view->name] = $view;

  return $views;
}


/**
 * Implements hook_block_info().
 *
 */
function lbd_wiki_block_info() {
  $block['book_outline'] = array(
    'info' => 'Book Outline',
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -100,
    'pages' => "<?php return lbd_wiki_is_book_node() != NULL ?>", 
    'region' => "sidebar_second",
  );

  $block['book_outline_2'] = array(
    'info' => 'Book Outline (inline)',
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => 0,
    'pages' => "<?php return lbd_wiki_is_book_node() != NULL ?>", 
    'region' => "none",
  );
  return $block;
}


/**
 * Cut a branch from a book tree 
 *
 * @param array $tree
 *   The tree
 * @param array $nodeId
 *   The node ID from which to cut a branch 
 *
 * @return array
 *   The branch
 */
function _tree_cut_branch($tree, $nodeId) {
  foreach($tree as $child1) {
    if($child1['link']['link_path'] == 'node/' . $nodeId)
      return $child1['below'];
    foreach($child1['below'] as $child2) {
      if($child2['link']['link_path'] == 'node/' . $nodeId)
        return $child2['below'];
      foreach($child2['below'] as $child3) {
        if($child3['link']['link_path'] == 'node/' . $nodeId)
          return $child3['below'];
        foreach($child3['below'] as $child4) {
          if($child4['link']['link_path'] == 'node/' . $nodeId)
            return $child4['below'];
          foreach($child4['below'] as $child5) {
            if($child5['link']['link_path'] == 'node/' . $nodeId)
              return $child5['below'];
          }
        }
      }
    }
  }
  return($tree);
}


/**
 * Implements hook_block_view().
 *
 */
function lbd_wiki_block_view($delta = '') {
  global $wikiLastChildrenMenuLink;
  global $wikiLastChildrenMenuLinkTime;
  $currentTime = time();
  $printTOC = TRUE;
  $defaultLanguage = language_default();
  global $language;
  global $user;
  $code = "";

  if($delta != 'book_outline' && $delta != 'book_outline_2')
    return NULL;

  $book = lbd_wiki_is_book_node();
  if(!$book)
    return NULL;

  $nodeId = arg(1);

  if ($language->language != $defaultLanguage->language)
    $lang = '/' . $language->language;
  else
    $lang = '';

  // Vars and params for the menu_build_tree() function.
  $path = 'node/' . $book['bid'];

  // Note: We cache the children data structure for two reasons:
  //       (1) To not have to recalculate it twice since
  //           this function is invoked twice for each wiki
  //           page (one for book_outline another for book_outline_2).
  //       (2) Somehow there is an issue when invoking menu_build_tree()
  //           a second time with the exact same parameters. 
  if($wikiLastChildrenMenuLinkTime and (($currentTime - $wikiLastChildrenMenuLinkTime) < 5)) {
    $children = $wikiLastChildrenMenuLink;
  }
  else {
    $parent = menu_link_get_preferred($path, $book['menu_name']);
    $parameters = array(
      'only_active_trail' => FALSE,
      'min_depth' => $parent['depth'] + 0,
      'max_depth' => 5,
    );
    // Build the tree and block title.
    $children = menu_build_tree($parent['menu_name'], $parameters);
    $wikiLastChildrenMenuLink = $children;
    $wikiLastChildrenMenuLinkTime = $currentTime;
  }

  // Check if it is a single page book
  if(count($children) == 1) {
    $child = array_values($children)[0];
    if(count($child['below']) == 0) {
      // For single page wiki books, don't print the TOC
      $printTOC = FALSE;
    }
  }

  $code = $code . "<hr/>";
  // Back to wiki index link
  $code = $code . "<img src='/profiles/labdoo/files/pictures/arrow_left.png' style='width: 20px; height: 21px;'/>&nbsp;" .  
                  "<a href='../wiki-index'>" . t('Go to all wiki books') . "</span></a></p>";

  // Other translations link
  $nodeLoaded = node_load($book['bid']);
  $originalNodeId = labdoo_lib_get_field($nodeLoaded, 'field_reference_book', 'node', 'target_id');
  $allTranslationsURl = $lang. '/wiki-index?field_book_language_value=All&field_reference_book_target_id='.$originalNodeId;
  $metadata = "href='$allTranslationsURl'";
  if($delta == 'book_outline') {
    $code = $code . "<img src='/profiles/labdoo/files/pictures/conversation.png' style='width: 20px; height: 21px;'/>&nbsp;" . 
                    "<a $metadata>" . t('Other translations of this wiki page') . "</span></a></p>";
  }

  if($printTOC) {
    $userRoles = array_values($user->roles);
    if(in_array('wiki writer', $userRoles) || in_array('administrator', $userRoles)) { 
      $metadata = "href='$lang/admin/content/book/" . $book['bid'] . "'";
      $code = $code . "<img src='/profiles/labdoo/files/pictures/book.png' style='width: 20px; height: 19px;'/>&nbsp;" . 
                      "<a $metadata>" . t('Reorder this book\'s hierarchy') . "</span></a></p>";
    }

    if($delta == 'book_outline_2') { 
      $children = _tree_cut_branch($children, $nodeId); 
      $code = "";
      if($children) {
        $code = $code . "<hr/>";
        $code = $code . t("<strong><font color='red'>Continue reading under this section:</font></strong>");
        $code = $code . "<hr/>";
      }
      else {
        // This node has no children, make it's next node (if any) become its child
        $loadedNode = node_load($nodeId);
        $nextBook = book_next($loadedNode->book);
        if($nextBook) {
          $nextChild = array();
          $nextChild['link'] = array();
          $nextChild['link']['link_path'] = $nextBook['link_path'];
          $nextChild['link']['link_title'] = $nextBook['link_title'];
          $code = $code . "<hr/>";
          $code = $code . t("<strong><font color='red'>Continue reading to the next page:</font></strong>"); 
          $code = $code . "<hr/>";
          $code = $code . _process_child($nextChild, $nodeId, 1);
        }
        $prevBook = book_prev($loadedNode->book);
        if($prevBook) {
          $prevChild = array();
          $prevChild['link'] = array();
          $prevChild['link']['link_path'] = $prevBook['link_path'];
          $prevChild['link']['link_title'] = $prevBook['link_title'];
          $code = $code . "<hr/>";
          $code = $code . t("<strong><font color='red'>Go back to read the previous page:</font></strong>"); 
          $code = $code . "<hr/>";
          $code = $code . _process_child($prevChild, $nodeId, 1);
        }
      }
    }
    else {
      $code = $code . "<hr/>";
      $code = $code . t("<strong><font color='gray'>Table of Content:</font></strong>");
      $code = $code . "<hr/>";
    }

    foreach($children as $child1) {
      $code = $code . _process_child($child1, $nodeId, 0);
      foreach($child1['below'] as $child2) {
        if($delta == 'book_outline_2')
          break; // For book_outline_2, only print one level
        $code = $code . _process_child($child2, $nodeId, 1);
        foreach($child2['below'] as $child3) {
          $code = $code . _process_child($child3, $nodeId, 2);
          foreach($child3['below'] as $child4) {
            $code = $code . _process_child($child4, $nodeId, 3);
            foreach($child4['below'] as $child5) {
              $code = $code . _process_child($child5, $nodeId, 4);
            }
          }
        }
      }
    }
  }

  // Build and return the $block array.
  // $book_name = (book_toc($book['bid'], 1));
  $block['subject'] = '<none>'; // l($book_name[$book['p1']], 'node/' . $book['bid']);
  $block['content'] = array('#markup' => $code);

  return $block;
}


/**
 *
 * Generates renderable (table of content) code for each child.
 *
 * @param array $child
 *   A book page child array
 * @param integer $nodeId
 *   The ID of the node currently being visited
 * @param integer $level
 *   The level of the node in its tree 
 *
 */ 
function _process_child($child, $nodeId, $level) {
  global $language;
  $defaultLanguage = language_default();
  $paddingLeft = $level * 10;
  $path = $child['link']['link_path'];
  $heading = $child['link']['link_title'];
  $nicePath = drupal_get_path_alias($path, $language->language);
  if($language->language != $defaultLanguage->language)
    $nicePath = $language->language . "/" . $nicePath;
  $metadata = "href='/$nicePath'";
  if($path == 'node/' . $nodeId)
    $metadata = "style='padding-left: " . $paddingLeft . "px;  display:block; background-color:#e6e6fa; color:#ff0000;'";
  else
    $metadata = "href='/$nicePath' style='padding-left: " . $paddingLeft . "px;  display:block'";
  $code = "<a $metadata>" . $heading . "</span></a></p>";
  return $code;
}


/**
 * Checks to see if current node is part of a book.
 *
 * @return array
 *   book portion of the node array if it is part of a book, FALSE if not
 */
function lbd_wiki_is_book_node() {
  if(!labdoo_lib_node_is_type(array('book'), FALSE))
    return FALSE;
  $node = menu_get_object();
  if ($node && isset($node->book)) {
    return $node->book;
  }
  return FALSE;
}


/**
 * Implements hook_menu_local_tasks_alter
 *
 */
function lbd_wiki_menu_local_tasks_alter(&$data) {
  global $user;
  // Hide Outline tab (reordering of book hierarchy is provided in the TOC block)
  if(sizeof($data['tabs']) > 0) {
    foreach($data['tabs'][0]['output'] as $key => $value) {
      if($value['#link']['path'] == "node/%/outline") {
        unset($data['tabs'][0]['output'][$key]);
      }
//      if($value['#link']['path'] == "node/%/revisions") {
//        $userRoles = array_values($user->roles);
//        if(!in_array('wiki writer', $userRoles) && !in_array('administrator', $userRoles)) {
//          unset($data['tabs'][0]['output'][$key]);
//        }
//      }
    }
    if(sizeof($data['tabs'][0]['output']) == 1) {  // Hide the redundant View tab 
      foreach($data['tabs'][0]['output'] as $key => $value) {
        if($value['#link']['path'] == "node/%/view") {
          unset($data['tabs'][0]['output'][$key]);
        }
      }
    }
  }
  return;
}


/**
 * Implements hook_form_FORM_ID_alter
 *
 */
function lbd_wiki_form_node_form_alter(&$form, &$form_state) {
  if (book_type_is_allowed($form['#node']->type)) {
    // Remove the "none" option.
    unset($form['book']['bid']['#options'][0]);
  }
}


/**
 * Validation of a wiki page content. 
 * Approach: validate that it is XML compliant.
 * This validation is specially important because 
 * if the wiki page written is not XML compliant,
 * the wiki backup system will not work.
 */


/**
 * Validates a wiki body
 *
 * @param string $wikiText
 *   The body of a wiki page
 * @return int
 *   The number of incorrections (0 if the validation succeeded)
 *
 */ 
function _validate_wiki_body($wikiText) {
  $numErrors = 0;
  $okErrorCodes = array();
  array_push($okErrorCodes, 0);

  libxml_use_internal_errors(true);

  $xmlstr = "<__wikibook__>" . $wikiText . "</__wikibook__>"; # Add dummy initial markup as the parser expects 
  $doc = simplexml_load_string($xmlstr);
  $wikiLines = explode("\n", $xmlstr);
  $errors = libxml_get_errors();

  if(count($errors) > 0){
    foreach ($errors as $error) {
      if(in_array($error->code, $okErrorCodes))
        continue;
      drupal_set_message(_display_wiki_error($error, $wikiLines));
      $numErrors++;
    }
    libxml_clear_errors();
  }

  return $numErrors;
}


/**
 * Returns a formatted wiki validation error
 *
 * @param string $error
 *   The error
 * @param array $wikiLines 
 *   An array of the lines of the wiki text 
 * @return string 
 *   The ready to display formatted error
 *
 */ 
function _display_wiki_error($error, $wikiLines) {

    switch ($error->level) {
        case LIBXML_ERR_WARNING:
            $return = "(Warning) ";
            break;
         case LIBXML_ERR_ERROR:
            $return = "";
            break;
        case LIBXML_ERR_FATAL:
            $return = "";
            break;
    }

    $return .= "Line: $error->line | Column: $error->column: ";
    $return .= trim($error->message) . "<br/>";
    $code = $wikiLines[$error->line - 1];
    $code = str_replace("<__wikibook__>", "", $code);   
    $code = str_replace("</__wikibook__>", "", $code);
    $return .= "<pre>" . check_plain($code) . "</pre>";

#   if ($error->file) {
#     $return .= "\n  File: $error->file";
#   }

    return "$return";
}


/*
 * Call back function to validate wiki text
 */
function _validate_wiki_text($form, &$form_state) {
  $lang = $form['body']['#language'];
  $body = $form['body'][$lang][0]['value']['#value'];
  $numErrors = _validate_wiki_body($body);
  if($numErrors > 0)
    form_set_error('title', t('Your wiki text has @numerr formatting errors, please review and correct them.', 
                              array('@numerr' => $numErrors)));
  return;
}


/*
 * Implementation of hook_form_alter
 */
function lbd_wiki_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'book_node_form') {
    $form['#validate'][] = '_validate_wiki_text';
  }

  return;
} 


/*
 * Implemetation of hook_node_view
 */
function lbd_wiki_node_view($node, $view_mode, $langcode) {

  if($node->type == "book") {
    // Render book_outline_2 right under the main content of the wiki
    // node. For some reason trying to do this by controling the weights
    // from https://www.labdoo.org/admin/structure/block does not work as
    // it always displays the 'Main page content' below this outline. 
    // Even trying to manually change the DB weights in the block does
    // not work (the weights in the DB are correct, so that is not the
    // issue). We resolve to use the hook node_view to have full control
    // of where the outline is displayed, by using the weight parameter
    // here.
    $block = module_invoke('lbd_wiki', 'block_view', 'book_outline_2');
    $node->content['wiki_boot_outline'] = array(
      '#markup' => render($block['content']),
      '#weight' => 100,
    );

    // Print message to tell readers how to provide feedback
    $path = drupal_get_path_alias(current_path());
    if(strcmp($path, "content/about-labdoo") != 0 &&
       strcmp($path, "content/acerca-de-labdoo") != 0 &&
       strcmp($path, "content/circa-labdoo") != 0 &&
       strcmp($path, "content/labdoo介绍") != 0 &&
       strcmp($path, "content/sobre-labdoo") != 0 &&
       strcmp($path, "content/zu-labdoo") != 0 &&
       strcmp($path, "content/關於labdoo") != 0) {
       strcmp($path, "content/getting-my-mini-missions-going") != 0 &&
       labdoo_lib_msg_info("If you have any questions about this page or if you find any errors,
                            please write a message to the 
                            <a href='../content/labdoo-global-support-lgs/activities'>support wall</a> 
                            and a Labdoo volunteer will help resolve it. 
                            Thank you for helping to improve our wiki pages.");
    }
  }
  return;
}


/**
 * Returns the list of book predecessors
 *
 * @param array $node 
 *   The book page from which to return the predecessors 
 *
 * @return array
 *   The list of node IDs corresponding to the predecessors
 *
 */
function _get_predecessors($node) {
  $predecessors = array();
  $iterNode = $node;
  
  while($iterNode->book['plid'] != 0) {
    $mlid = menu_link_load($iterNode->book['plid']);
    $parentNid = explode('node/', $mlid['link_path'])[1];
    $predecessors[] = $parentNid;
    $iterNode = node_load($parentNid);
  }
  return $predecessors;
}


/**
 * Implements hook_node_access
 *
 */
function lbd_wiki_node_access($node, $op, $account) {
  global $user;

  if($op == "update" && $node->type == "book") {
    $predecessorsList = _get_predecessors($node);
    foreach($predecessorsList as $predecessor) {
      $nodeLoaded = node_load($predecessor);
      $editors = labdoo_lib_get_field_all($nodeLoaded, 'field_grant_edit_rights_wiki', 'node', 'target_id');
      if(in_array($user->uid, $editors))
        return NODE_ACCESS_ALLOW;
    }
    return NODE_ACCESS_IGNORE; 
  }

  return;
}

