<?php

/**
 * @defgroup labdooblocksview LabdooBlocksView Labdoo Blocks and Views 
 *
 * This module implements all the Labdoo blocks and views 
 *
 */


/**
 * @file
 * Main module file for the Labdoo Blocks and Views module 
 *
 * @ingroup labdooblocksview
 *
 */


/*
 * ==========
 * VIEWS CODE
 * ==========
 */

/**
 * Implementation of hook_views_api
 */
function lbd_blocks_views_views_api() {
  return array(
    'api' => 3.0,
  );
} 


/**
 * Implementation of hook_views_default_views
 */
function lbd_blocks_views_views_default_views() {

  // Global inventory view
  include 'lbd_blocks_views_global_inventory.inc';
  $views[$view->name] = $view;

  // Actions feed view
  include 'lbd_blocks_views_actions.inc';
  $views[$view->name] = $view;

  // Slider dashboard view
  include 'lbd_blocks_views_slider_dashboard.inc';
  $views[$view->name] = $view;

  // Newsletters view
  include 'lbd_blocks_views_newsletters.inc';
  $views[$view->name] = $view;

  return $views;
}


/*
 * ==========
 * BLOCKS CODE
 * ==========
 */

/**
 * Implementation of hook_block_info 
 */
function lbd_blocks_views_block_info() {

  // Geolocation map for nodes
  $blocks['block_geolocation_map_node'] = array(
    'info' => "Geolocation map for nodes",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -90,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('laptop' => 1,'dootrip' => 1,'hub' => 1, 'edoovillage' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  // Dooject header
  $blocks['block_dooject_header'] = array(
    'info' => "The header of a dooject",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -100,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('laptop' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  // Edoovillage header
  $blocks['block_edoovillage_header'] = array(
    'info' => "The header of an edoovillage",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -100,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('edoovillage' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  // Block linking to the language switcher dropdown block
  $blocks['block_link_language_switch'] = array(
    'info' => "Language switch (link to language switcher dropdown block)",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -50,
    'pages' => "
<?php
  \$path = drupal_get_path_alias(current_path());
  if(strpos(\$path, \"content/tag-one-dooject\") !== FALSE)
      return FALSE;
  \$views_page = views_get_page_view();
  if (is_object(\$views_page)) {
    if(\$views_page->name == \"global_inventory\")
      return FALSE; 
  }
  return TRUE;
?>
               ",
    'region' => "sidebar_second",
  );

  // Block linking to the actions feed block
  $blocks['block_link_actions_feed'] = array(
    'info' => "Actions feed (link to actions feed block)",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -60,
    'pages' => "
<?php
  \$path = drupal_get_path_alias(current_path());
  if(strpos(\$path, \"content/tag-one-dooject\") !== FALSE)
      return FALSE;
  \$views_page = views_get_page_view();
  if (is_object(\$views_page)) {
    if(\$views_page->name == \"global_inventory\")
      return FALSE; 
  }
  return TRUE;
?>
               ",
    'region' => "sidebar_second",
  );

  return $blocks;
}


/**
 * Implementation of hook_block_view 
 */
function lbd_blocks_views_block_view($delta = '') {
  $block = array();

  switch ($delta) {

    // Geolocation map for nodes
    case 'block_geolocation_map_node':
      $block['subject'] = "<none>";
      $block['content'] = array(
             '#markup' => labdoo_render_map_geolocate_node(),
      );
      break;

    // Dooject header
    case 'block_dooject_header':
      $block['subject'] = "<none>";
      $block['content'] = array(
             '#markup' => labdoo_render_dooject_header(),
      );
      break;

    // Edoovillage header
    case 'block_edoovillage_header':
      $block['subject'] = "<none>";
      $block['content'] = array(
             '#markup' => labdoo_render_edoovillage_header(),
      );
      break;

    // Language switch
    case 'block_link_language_switch':
      $blockLanguage = module_invoke('lang_dropdown', 'block_view', 'language');
      $block['subject'] = "<none>";
      $block['content'] = drupal_render($blockLanguage["content"]);
      break;

    // Actions feed 
    case 'block_link_actions_feed':
      $blockActions = module_invoke('views', 'block_view', 'actions-block');
      $block['subject'] = "<none>";
      $block['title'] = t("Mini-missions");
      $block['content'] = drupal_render($blockActions["content"]);
      break;

  }

  return $block;
}

