<?php

/**
 * @defgroup labdooblocksview LabdooBlocksView Labdoo Blocks and Views 
 *
 * This module implements all the Labdoo blocks and views 
 *
 */


/**
 * @file
 * Main module file for the Labdoo Blocks and Views module 
 *
 * @ingroup labdooblocksview
 *
 */


/*
 * ==========
 * VIEWS CODE
 * ==========
 */

/**
 * Implementation of hook_views_api
 */
function lbd_blocks_views_views_api() {
  return array(
    'api' => 3.0,
  );
} 


/**
 * Implementation of hook_views_default_views
 */
function lbd_blocks_views_views_default_views() {

  // Global inventory view
  include 'lbd_blocks_views_global_inventory.inc';
  $views[$view->name] = $view;

  // Actions feed view
  include 'lbd_blocks_views_actions.inc';
  $views[$view->name] = $view;

  // Slider dashboard view
  include 'lbd_blocks_views_slider_dashboard.inc';
  $views[$view->name] = $view;

  // Newsletters view
  include 'lbd_blocks_views_newsletters.inc';
  $views[$view->name] = $view;

  return $views;
}


/*
 * ==========
 * BLOCKS CODE
 * ==========
 */

/**
 * Implementation of hook_block_info 
 */
function lbd_blocks_views_block_info() {

  // Geolocation map for nodes
  $blocks['block_geolocation_map_node'] = array(
    'info' => "Geolocation map for nodes",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -90,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('laptop' => 1,'dootrip' => 1,'hub' => 1, 'edoovillage' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  // Dooject header
  $blocks['block_dooject_header'] = array(
    'info' => "The header of a dooject (2)",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -100,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('laptop' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  // Edoovillage header
  $blocks['block_edoovillage_header'] = array(
    'info' => "The header of an edoovillage",
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_PHP,
    'weight' => -100,
    'pages' => "
<?php
  \$match = FALSE;
  \$types = array('edoovillage' => 1) ;

  if ((arg(0) == 'node') && is_numeric(arg(1))) {
    \$node = node_load(arg(1));
    \$match = isset(\$types[\$node->type]);
  }

  return \$match;
?>
               ",
    'region' => "content",
  );

  return $blocks;
}


/**
 * Implementation of hook_block_view 
 */
function lbd_blocks_views_block_view($delta = '') {

  switch ($delta) {
    // Geolocation map for nodes
    case 'block_geolocation_map_node':
      $block['subject'] = "<none>";
      $block['content'] = labdoo_render_map_geolocate_node();
      break;

    // Dooject header
    case 'block_dooject_header':
      $block['subject'] = "<none>";
      $block['content'] = labdoo_render_dooject_header();
      break;

    // Edoovillage header
    case 'block_edoovillage_header':
      $block['subject'] = "<none>";
      $block['content'] = labdoo_render_edoovillage_header();
      break;
  }

  return $block;
}

