** Introduction

This document describes the steps needed to translate the Labdoo.org social network platform.

** Steps to translate Labdoo.org

*** Translation of portable object (.po) files (estimated time 2 hours)

+ Go to https://github.com/Labdoo/Labdoo/tree/master/translations/po-files/templates/labdoo-translation-fields.po

+ Right click on the button "Raw", select the option 'Save link as' and download the file into your local computer.

+ To translate the file, search for all occurrences of the keyword 'msgstr ""' and include into the quote "" the translation of the English words found in the field 'msgid'.

+ Save the translated file using the same file name but adding a suffix to reflect the language you are translating to. For instance, if you are translating to Japanese, save the filename as 'labdoo-translation-fields-japanese.po'. 

*** Translation of email (.email) files (estimated time 2 hours)

+ Go to https://github.com/Labdoo/Labdoo/tree/master/translations/email-files/en

+ Translate each of the files you will find in this folder.

+ Save each translation file using the same original file name but changing its suffix to reflect the language you are translating to. For instance, if you are translating to Japanese the file 'dootrip_added_body-en.email', rename the translated file to 'dootrip_added_body-japanese.email'. 

*** Where to send the translated files

+ Once you are done with your translations, send the translated files to the email address project-labdoo@labdoo.org using as subject 'Labdoo.org translation files'.

