<?php

/**
 * @defgroup labdoomenu LabdooMenu Labdoo Menus 
 *
 * This module implements all the Labdoo menus
 *
 */


/**
 * @file
 * Main module file for the Labdoo Menus module 
 *
 * @ingroup labdoomenu
 *
 */


/**
 *
 * Creates the main menu
 *
 */
function make_main_menu() {

  // Delete first any initial menus
  menu_delete_links("main-menu");

  /*
   * Explore menu item
   */
  $item = array(
            'link_path' => 'actions',
            'link_title' => 'Explore',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -60,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $exploreMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'actions',
            'link_title' => 'Actions',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'map',
            'link_title' => 'Global inventory',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'dootrips',
            'link_title' => 'Dootrips inventory',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -38,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'labdooers',
            'link_title' => 'Labdooers',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -35,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid,
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'newsletters',
            'link_title' => 'Newsletters',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Doojects menu item
   */
  $item = array(
            'link_path' => 'node/44',
            'link_title' => 'Doojects',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('A dooject is a device that can be used for education (laptop, tablet, smartphone, etc.)');
  $doojectMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/laptop',
            'link_title' => 'Tag',
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $doojectMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/44',
            'link_title' => 'View',
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $doojectMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Edoovillages menu item
   */
  $item = array(
            'link_path' => 'node/45',
            'link_title' => 'Edoovillages',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('An edoovillage is an education center where doojects are deployed');
  $edoovillageMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/edoovillage',
            'link_title' => 'Create',
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/45',
            'link_title' => 'View',
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Hubs menu item
   */
  $item = array(
            'link_path' => 'node/46',
            'link_title' => 'Hubs',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -20,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('A hub is a group of labdooers united to help bring doojects to edoovillages');
  $hubMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/hub',
            'link_title' => 'Create',
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/46',
            'link_title' => 'View',
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Dootrips menu item
   */
  $item = array(
            'link_path' => 'node/47',
            'link_title' => 'Dootrips',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('A dootrip is a CO2-neutral route donated by travelers to bring doojects to edoovillages');
  $dootripMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/dootrip',
            'link_title' => 'Create',
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/47',
            'link_title' => 'View',
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Newsletter menu item
   */
  $item = array(
            'link_path' => 'node/add/simplenews',
            'link_title' => 'Newsletters',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -10,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('To help bring awareness and outreach your local community, you can create your own newsletter');
  $newsletterMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/simplenews',
            'link_title' => 'Create an issue',
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $newsletterMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'admin/config/services/simplenews',
            'link_title' => 'Manage',
            'menu_name' => 'main-menu',
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $newsletterMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  return;
}


/*
 * Implements hook_menu
 *
 */
function lbd_menus_menu() {

  /*
   * Dynamic menu items go here.
   *
   * Examples of dynamic parameters:
   *   - Links that depend on the user id
   *   - Visibility that depends on the user's role
   *
   */

  $menus['myDoojects'] = array
  (
    'title' => 'My doojects',
    'page callback' => '_menu_item_redirect_my_doojects',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myEdoovillages'] = array
  (
    'title' => 'My edoovillages',
    'page callback' => '_menu_item_redirect_my_edoovillages',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myHubs'] = array
  (
    'title' => 'My hubs',
    'page callback' => '_menu_item_redirect_my_hubs',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myDootrips'] = array
  (
    'title' => 'My dootrips',
    'page callback' => '_menu_item_redirect_my_dootrips',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myActionsList'] = array
  (
    'title' => 'My actions',
    'page callback' => '_menu_item_redirect_my_actions',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  /*
   * URL redirects go here
   */
 $menus['content/dashboard-slider'] = array
  (
    'title' => 'My dashboard',
    'page callback' => '_menu_item_redirect_my_dashboard',
    'access callback' => TRUE,
  );

  return $menus;
}


/*
 * Callback functions to redirect dynamic menu items
 *
 */ 
function _menu_item_redirect_my_doojects() {
  global $user; 
  drupal_goto('content/doojects-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_edoovillages() {
  global $user; 
  drupal_goto('content/edoovillages-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_hubs() {
  global $user; 
  drupal_goto('content/hubs-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_dootrips() {
  global $user; 
  drupal_goto('content/dootrips-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_actions() {
  drupal_goto('myActions');
  return;
}


/*
 * Callback functions to redirect certain URLs.
 *
 */ 
function _menu_item_redirect_my_dashboard() {
  /*
   * Callback function used to preserve compatibility
   * with the dashboard URL in Labdoo 1.0 
   */
  global $user; 
  drupal_goto('');
  return;
}


/*
 * Implements hook_menu_link_alter
 * Used to connect dynamic menu items with their proper 
 * parent menu item
 *
 */
function lbd_menus_menu_link_alter(&$item) {
  
 if ($item['page callback'] == '_menu_item_redirect_my_doojects') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/44' AND link_title='Doojects' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_edoovillages') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/45' AND link_title='Edoovillages' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_hubs') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/46' AND link_title='Hubs' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_dootrips') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/47' AND link_title='Dootrips' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_actions') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='actions' AND link_title='Explore' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  return;
}


/**
 *
 * Creates the main menu
 *
 */
function clean_main_menu() {
  menu_delete_links("main-menu");
  return;
}

