<?php

/**
 * @defgroup labdoomenu LabdooMenu Labdoo Menus 
 *
 * This module implements all the Labdoo menus
 *
 */


/**
 * @file
 * Main module file for the Labdoo Menus module 
 *
 * @ingroup labdoomenu
 *
 */


/**
 *
 * Creates the main menu
 *
 */
function make_main_menu() {

  // Delete first any initial menus
  menu_delete_links("main-menu");

  /*
   * Explore menu item
   */
  $item = array(
            'link_path' => 'actions',
            'link_title' => t('Explore'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -60,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Explore the Labdoo platform using a variety of tools');
  $exploreMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'actions',
            'link_title' => t('Actions'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Labdoo for Companies (CSR)'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -45,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'map',
            'link_title' => t('Global inventory'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'dootrips',
            'link_title' => t('Dootrips inventory'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -38,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Dootrips are CO2-neutral routes donated by travelers to help bring education devices to schools');
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'hubs',
            'link_title' => t('Hubs (tree view)'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -35,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid,
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'newsletters',
            'link_title' => t('Newsletters'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'http://ftp.labdoo.org/download',
            'link_title' => t('FTP resources'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -28,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -25,
            'customized' => 1,
            'plid' => $exploreMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'labdooers',
            'link_title' => 'Labdooers',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -20,
            'language' => 'en',
            'customized' => 1,
            'plid' => $exploreMlid,
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  // TODO: In the following menu items, we use hardcoded node IDs for the 'link_path'.
  //       For some reason it does not take general URLs. Fix this by using 
  //       supporting functions such as drupal_get_path_alias(). 

  /*
   * Dootronics menu item
   */
  $item = array(
            'link_path' => 'node/11',
            'link_title' => 'Dootronics',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Dootronics (Labdoo electronics) are education devices such as laptops, tablets, eBooks that are donated to schools');
  $dootronicMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/11',
            'link_title' => t('View'),
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootronicMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Note: menu items pointing to static pages whose node ID is not known
   * at the time this module is installed (such as menu items pointing 
   * to the wiki like the 'About ...' links) are set to point to the
   * front page '<front>' and hence these menu items require to be
   * manually adjusted
   */
  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about dootronics'),
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $dootronicMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -45,
            'customized' => 1,
            'plid' => $dootronicMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/laptop',
            'link_title' => t('Tag it!'),
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootronicMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Edoovillages menu item
   */
  $item = array(
            'link_path' => 'node/12',
            'link_title' => 'Edoovillages',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Edoovillages are schools and education centers where the dootronics are deployed');
  $edoovillageMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/12',
            'link_title' => t('View'),
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about edoovillages'),
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -45,
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/edoovillage',
            'link_title' => t('Create'),
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $edoovillageMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Hubs menu item
   */
  $item = array(
            'link_path' => 'node/13',
            'link_title' => t('Hubs'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -20,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Hubs are groups of labdooers located in the same region that together help mobilize dootronics from their local community');
  $hubMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/13',
            'link_title' => t('View'),
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about hubs'),
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -45,
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/hub',
            'link_title' => t('Create'),
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'hubs',
            'link_title' => t('View (tree mode)'),
            'menu_name' => 'main-menu',
            'weight' => 5,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/superhub-page',
            'link_title' => t('[Superhub] Create content'),
            'menu_name' => 'main-menu',
            'weight' => 10,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'superhub-pages',
            'link_title' => t('[Superhub] List content'),
            'menu_name' => 'main-menu',
            'weight' => 20,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );

  $item = array(
            'link_path' => 'admin/config/system/google_adwords/path',
            'link_title' => t('[Superhub] Manage adwords'),
            'menu_name' => 'main-menu',
            'weight' => 30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $hubMlid, 
            'module' => 'menu',
          );
 
  $mlid = menu_link_save($item);

  /*
   * Dootrips menu item
   */
  $item = array(
            'link_path' => 'node/14',
            'link_title' => 'Dootrips',
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $dootripMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/14',
            'link_title' => t('View'),
            'menu_name' => 'main-menu',
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about dootrips'),
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -45,
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/dootrip',
            'link_title' => t('Create'),
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $dootripMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Teams menu item
   */
  $item = array(
            'link_path' => 'teams',
            'link_title' => t('Teams'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -15,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Teams provide a set of tools to help Labdoo users organize themselves around topic areas');
  $teamsMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'teams',
            'link_title' => t('List all teams'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -36,
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'teams-activities',
            'link_title' => t('Teams wall'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'my-teams',
            'link_title' => t('List my teams'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -35,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'my-teams-activities',
            'link_title' => t('My teams wall'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/team',
            'link_title' => t('Create a team'),
            'menu_name' => 'main-menu',
            'weight' => -29,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'teams-dashboard',
            'link_title' => t('Search inside teams'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -38,
            'language' => 'en',
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about teams'),
            'menu_name' => 'main-menu',
            'weight' => -35,
            'customized' => 1,
            'plid' => $teamsMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Newsletter menu item
   */
  $item = array(
            'link_path' => 'node/add/simplenews',
            'link_title' => t('Newsletters'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -10,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Newsletters are used to help outreach your local community');
  $newsletterMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/simplenews',
            'link_title' => t('Create an issue'),
            'menu_name' => 'main-menu',
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $newsletterMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'admin/config/services/simplenews',
            'link_title' => t('Manage'),
            'menu_name' => 'main-menu',
            'weight' => -30,
            'language' => 'en',
            'customized' => 1,
            'plid' => $newsletterMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about newsletters'),
            'menu_name' => 'main-menu',
            'weight' => -25,
            'customized' => 1,
            'plid' => $newsletterMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  /*
   * Wiki menu item
   */
  $item = array(
            'link_path' => 'wiki-index',
            'link_title' => t('Wiki'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => -10,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('The wiki is where everything gets docummented');
  $wikiMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'wiki-index',
            'link_title' => t('Index'),
            'menu_name' => 'main-menu',
            'expanded' => true,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $wikiMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<front>',
            'link_title' => t('Help about the wiki'),
            'menu_name' => 'main-menu',
            'weight' => -49,
            'customized' => 1,
            'plid' => $wikiMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $wikiMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => 'node/add/book',
            'link_title' => t('Add new content'),
            'menu_name' => 'main-menu',
            'expanded' => true,
            'weight' => -40,
            'language' => 'en',
            'customized' => 1,
            'plid' => $wikiMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

   /*
   * User menu item
   */
  $item = array(
            'link_path' => 'user',
            'link_title' => t('My account'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => 10,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('Log in/out and manage my account');
  $userMlid = menu_link_save($item);

  /*
   * Share wall menu item
   */
  $item = array(
            'link_path' => 'share-wall',
            'link_title' => t('Share wall'),
            'menu_name' => 'main-menu',
            'expanded' => TRUE,
            'weight' => 0,
            'language' => 'en',
            'customized' => 1,
            'plid' => 0, 
            'module' => 'menu',
          );
  $item['options']['attributes']['title'] = t('In the wall you can share your pictures and activities with the rest of the Labdooers');
  $shareMlid = menu_link_save($item);

  $item = array(
            'link_path' => 'share-wall',
            'link_title' => t('Global share wall'),
            'menu_name' => 'main-menu',
            'expanded' => true,
            'weight' => -50,
            'language' => 'en',
            'customized' => 1,
            'plid' => $shareMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  $item = array(
            'link_path' => '<separator>',
            'menu_name' => 'main-menu',
            'weight' => -48,
            'customized' => 1,
            'plid' => $shareMlid, 
            'module' => 'menu',
          );
  $mlid = menu_link_save($item);

  return;
}


/*
 * Implements hook_menu
 *
 */
function lbd_menus_menu() {

  /*
   * Dynamic menu items go here.
   *
   * Examples of dynamic parameters:
   *   - Links that depend on the user id
   *   - Visibility that depends on the user's role
   *
   */

  $menus['myDootronics'] = array
  (
    'title' => 'My dootronics',
    'page callback' => '_menu_item_redirect_my_dootronics',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myEdoovillages'] = array
  (
    'title' => 'My edoovillages',
    'page callback' => '_menu_item_redirect_my_edoovillages',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myHubs'] = array
  (
    'title' => 'My hubs',
    'page callback' => '_menu_item_redirect_my_hubs',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myDootrips'] = array
  (
    'title' => 'My dootrips',
    'page callback' => '_menu_item_redirect_my_dootrips',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myActionsList'] = array
  (
    'title' => 'My actions',
    'page callback' => '_menu_item_redirect_my_actions',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myShareWall'] = array
  (
    'title' => 'My share wall',
    'page callback' => '_menu_item_redirect_my_sharewall',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['myWikis'] = array
  (
    'title' => 'My wiki articles',
    'page callback' => '_menu_item_redirect_my_wikis',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $menus['logIn'] = array
  (
    'title' => 'Log in',
    'page callback' => '_menu_item_redirect_log_in',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -100, 
  );

  $menus['createAccount'] = array
  (
    'title' => 'Create a new account',
    'page callback' => '_menu_item_redirect_create_account',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -90, 
  );

  $menus['logOut'] = array
  (
    'title' => 'Log out',
    'page callback' => '_menu_item_redirect_log_out',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => 100, 
  );

  $menus['gettingStarted'] = array
  (
    'title' => 'Getting started',
    'page callback' => '_menu_item_redirect_getting_started',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -85, 
  );

  $menus['myContributions'] = array
  (
    'title' => 'My global contributions',
    'page callback' => '_menu_item_redirect_my_contributions',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -80, 
  );

  $menus['editProfile'] = array
  (
    'title' => 'Edit my profile',
    'page callback' => '_menu_item_redirect_edit_profile',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -70, 
  );

  $menus['editAccount'] = array
  (
    'title' => 'Edit my account',
    'page callback' => '_menu_item_redirect_edit_account',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -60, 
  );

  $menus['myEvents'] = array
  (
    'title' => 'My events',
    'page callback' => '_menu_item_redirect_my_events',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50, 
  );

  $menus['myRoles'] = array
  (
    'title' => 'My roles',
    'page callback' => '_menu_item_redirect_my_roles',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -40, 
  );

  $menus['manageFiles'] = array
  (
    'title' => 'Manage files',
    'page callback' => '_menu_item_redirect_manage_files',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -30, 
  );


  /*
   * URL redirects go here
   */
  $menus['content/dashboard-slider'] = array
  (
    'title' => 'My dashboard',
    'page callback' => '_menu_item_redirect_my_dashboard',
    'access callback' => TRUE,
  );

  return $menus;
}


/*
 * Callback functions to redirect dynamic menu items
 *
 */ 
function _menu_item_redirect_my_dootronics() {
  global $user; 
  drupal_goto('content/dootronics-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_edoovillages() {
  global $user; 
  drupal_goto('content/edoovillages-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_hubs() {
  global $user; 
  drupal_goto('content/hubs-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_dootrips() {
  global $user; 
  drupal_goto('content/dootrips-dashboard', array('query' => array('u' => $user->uid)));
  return;
}

function _menu_item_redirect_my_actions() {
  drupal_goto('myActions');
  return;
}

function _menu_item_redirect_my_sharewall() {
  drupal_goto('content/my-share-wall');
  return;
}

function _menu_item_redirect_my_wikis() {
  global $user; 
  drupal_goto('my-wikis', array('query' => array('uid' => $user->name)));
  return;
}

function _menu_item_redirect_log_in() {
  drupal_goto('user/login');
  return;
}

function _menu_item_redirect_create_account() {
  drupal_goto('user/register');
  return;
}

function _menu_item_redirect_log_out() {
  drupal_goto('user/logout');
  return;
}

function _menu_item_redirect_getting_started() {
  global $user; 
  drupal_goto('users/' . $user->name . '/gettingStarted');
  return;
}

function _menu_item_redirect_my_contributions() {
  global $user;
  drupal_goto('users/' . $user->name . '/metrics');
  return;
}

function _menu_item_redirect_show_profile() {
  global $user; 
  drupal_goto('users/' . $user->name);
  return;
}

function _menu_item_redirect_edit_profile() {
  global $user; 
  drupal_goto('user/' . $user->uid . '/edit-profile');
  return;
}

function _menu_item_redirect_edit_account() {
  global $user; 
  drupal_goto('user/' . $user->uid . '/edit');
  return;
}

function _menu_item_redirect_my_events() {
  global $user; 
  drupal_goto('users/' . $user->name . '/myevents');
  return;
}

function _menu_item_redirect_my_roles() {
  global $user; 
  drupal_goto('users/' . $user->name . '/myroles');
  return;
}

function _menu_item_redirect_manage_files() {
  global $user; 
  drupal_goto('users/' . $user->name . '/imce');
  return;
}

/*
 * Callback functions to redirect certain URLs.
 *
 */ 
function _menu_item_redirect_my_dashboard() {
  /*
   * Callback function used to preserve compatibility
   * with the dashboard URL in Labdoo 1.0 
   */
  global $user; 
  drupal_goto('');
  return;
}


/*
 * Implements hook_menu_link_alter
 * Used to connect dynamic menu items with their proper 
 * parent menu item
 *
 */
function lbd_menus_menu_link_alter(&$item) {

  if(!array_key_exists('page callback', $item))
    return;
  
  if ($item['page callback'] == '_menu_item_redirect_my_dootronics') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/11' AND link_title='Dootronics' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_edoovillages') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/12' AND link_title='Edoovillages' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_hubs') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/13' AND link_title='Hubs' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_dootrips') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='node/14' AND link_title='Dootrips' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_actions') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='actions' AND link_title='Explore' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_sharewall') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='share-wall' AND link_title='Share wall' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_wikis') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='wiki-index' AND link_title='Wiki' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_log_in') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_create_account') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_log_out') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_getting_started') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_contributions') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_show_profile') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_edit_profile') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_edit_account') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_events') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_my_roles') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

  if ($item['page callback'] == '_menu_item_redirect_manage_files') {
    $plid = db_query("SELECT mlid FROM menu_links WHERE link_path='user' AND link_title='My account' AND menu_name='main-menu'")->fetchField();
    $item['plid'] = $plid;
  }

 return;
}


/**
 *
 * Creates the main menu
 *
 */
function clean_main_menu() {
  menu_delete_links("main-menu");
  return;
}

