About Project Labdoo

Labdoo is a social network that is designed from the ground up to serve a social cause. We like to call it an aid social network  to denote that the goal is not to make money, but rather to serve a social cause. As such, Labdoo has several properties: 

- It is non-profit. 

- It is collaborative.

- It is fully distributed.

- The code that runs the social network is open and free (GPLv3).

- Anyone can participate.

- It is designed to enable the global Labdoo mission without incurring additional CO2 emissions.

- It requires no funding to run.

As indicated, the code that runs Labdoo is freely available. In fact, you can install an instance of the Labdoo social network in your local computer if you want; you can copy the code, modify and improve it. You can also use portions of the code to create your own social network if you want to serve other social causes. The code is available from https://github.com/Labdoo/Labdoo-2.0.  

This document provides a description of the features that the Labdoo social network implements.

* Feature Set

** [Feature 1] The five basic objects.

At its core, the Labdoo social network is based around five types of objects: labdooers, doojects, dootrips, edoovillages and hubs.

- Labdooers: Labdoo users.

- Doojects: Labdoo objects. The actual devices (objects) such as laptops, tablets, etc. that get loaded with education applications and transported to needy schools.

- Dootrips: Labdoo trips. CO2 neutral transportation means used to carry laptops from one location to another. Examples of dootrips are the trips carried out by tourists, NGO volunteers (doctors, engineers, etc.), international students, employees of international corporations, etc.

- Edoovillages: Schools who receive doojects such as laptops or tablets loaded with education software.

- Hubs: while everyone can participate (from home, from school, from work, etc.), labdooers find commonly useful to organize themselves locally as groups of volunteers. A hub is just that, a groups of labdooers located in a given region that get together to carry out Labdoo tasks.

Given their relevance, users can find on the main navigation menu bar of the Labdoo social network access to each of this five basic objects.

** [Feature 2] General layout: main navigation menu. 

The main layout of the Labdoo system is controlled via the main navigation menu (MNN), located at the top of the page. This allows users to quickly move to the various resources and tools. An important property of the MNN is that the availability of the various options depend on the role of the user. The more roles a user has, the more options he/she sees in the MNN.

** [Feature 3] Types of user roles. 

A user can have one of the following roles:

- Anonymous: corresponds to users who visit labdoo.org without logging into an an account. This users can only do “view” type of activites.

- Authenticated: corresponds to the very basic labdoo user role. This is the role that a labdooer receives by default when registering for the first time to the system. This type of account allows the user to perform some basic functions such as tagging laptops or registering a dootrip.

- Hub manager: provides basic functions to manage hubs.

- Edoovillage manager: provides functions to manage edoovillages.

- Newsletter manager: provides functions to manage edit and publish newsletters issues.

- Wiki writer: provides functions to write new wiki documents.

- Team manager: provides functions to help manage Labdoo teams.

- Superhub manager: provides functions to create new hubs and help manage larger Labdoo regions englobing multiple hubs.

** Visualization dashboards

TODO

** Labdoo Teams

TODO

** Translations

TODO

** Activities feeds

TODO

** Communications

TODO

** Global Inventory Checks (GICs)

TODO

** Photo Albums

TODO

** Progress Bars

TODO

** Downloading snapshots of work in progress

TODO

** REST API

TODO

** Tracking my contributions

TODO

** Outreaching using newsletters

TODO

** The Labdoo Wiki

TODO

** FTP resources

TODO

** My account

TODO

** Signals

TODO

- Automatic emails

- On page signals (relations between users and objects)

- Cron type of signals


