** Updates in Source Code's Top of Tree

  - To update the Drupal core to the latest release, edit the file 'drupal-org-core.make' and modify the value of 'projects[drupal][version]'. For example:

    #+BEGIN_EXAMPLE
    projects[drupal][version] = 7.39
    #+END_EXAMPLE

  - To update a Drupal module to the latest release, edit the file 'labdoo.make' and modify the value of the corresponding module. For example:

    #+BEGIN_EXAMPLE
    projects[ctools] = 1.9
    #+END_EXAMPLE

** Productions Updates

  To update the Labdoo production system, it's important to first perform the same type of update on a development instance to ensure all works well. 
  Be sure to also back up an instance of the production system prior to running the instructions below.

  - To update the Drupal core to the latest release, do as follows:

    #+BEGIN_EXAMPLE
    # Set the site under maintenance mode and clear the cache
    drush vset --exact maintenance_mode 1
    drush cache-clear all
    cp /var/www/lbd/.htaccess /var/www/lbd/.htaccess.backup
    cp /var/www/lbd/robots.txt /var/www/lbd/robots.txt.backup
    cp /var/www/lbd/sites/default/settings.php /var/www/lbd/sites/default/settings.php.backup
    drush up drupal
    # check if there were any changes to .htaccess, robots.txt and settings.php and if so, reapply them.
    diff /var/www/lbd/.htaccess /var/www/lbd/.htaccess.backup
    diff /var/www/lbd/robots.txt /var/www/lbd/robots.txt.backup
    diff /var/www/lbd/sites/default/settings.php /var/www/lbd/sites/default/settings.php.backup
    # Bring the site back and clear the cache one more time
    drush vset --exact maintenance_mode 0
    drush cache-clear all 
    #+END_EXAMPLE

  - To update a Drupal module to the latest release, do as follows:

    #+BEGIN_EXAMPLE
    drush vset --exact maintenance_mode 1
    drush @lbd up ctools google_analytics # list here the modules you want to update
    drush vset --exact maintenance_mode 0
    drush cache-clear all
    #+END_EXAMPLE

  - To update the Linux distribution software

    #+BEGIN_EXAMPLE
    sudo su
    apt-get update
    apt-get upgrade
    service chroot-lbd stop
    reboot
    [ssh back]
    sudo su
    mount /dev/xvdb1 /var/chroot/
    service chroot-lbd stop
    service chroot-lbd start
    hostname www.labdoo.org
    #+END_EXAMPLE

** Upgrading the Ubuntu OS

  - Upgrade of the base OS

    #+BEGIN_EXAMPLE
    XXX
    #+END_EXAMPLE

  - Upgrade of the jailed OS

    #+BEGIN_EXAMPLE
    XXX
    #+END_EXAMPLE

  - At the end of the above process, it's likely that you will need to update some of the configuration files, as the upgrade may have overwritten them. Make sure the following parameters are set as follows:

    #+BEGIN_EXAMPLE
    ==> # cat /etc/php/7.0/cli/php.ini | grep upload_max_filesize  # use the right version of php here
    upload_max_filesize = 20M

    ==> # cat /etc/php/7.0/cli/php.ini | grep post_max_size
    post_max_size = 21M

    ==> # cat /etc/php/7.0/apache2/php.ini | grep memory_limit
    memory_limit = 500M

    ==> # cat /etc/mysql/my.cnf | grep innodb_buffer_pool_size
    innodb_buffer_pool_size         = 3000M
    #+END_EXAMPLE

    ==> # head /usr/share/apache2/ask-for-passphrase
    echo "xxx"  # use the right password
    exit
    #+END_EXAMPLE

** Upgrading the hardware

    - Important: remember to update the instance ID in Labdoo's AWS AMI and Volume snapshot script to make sure the backups are done on the correct instance.

