** About Project Labdoo

Labdoo is a social network that is designed from the ground up to serve a social cause. We like to call it an aid social network to denote that the goal is not to make money, but rather to serve a social cause. As such, Labdoo has several properties: 

- It is non-profit. 

- It is collaborative.

- It is fully distributed.

- The code that runs the social network is open and free (GPLv3).

- Anyone can participate.

- It is designed to run without incurring additional CO2 emissions.

- It requires no funding to run.

- It is free from any type of advertisement.

As indicated, the code that runs Labdoo is freely available. In fact, you can install an instance of the Labdoo social network in your local computer if you want; you can copy the code, modify it, and improve it. You can also use portions of the code to create your own social network if you want to serve other social causes. The code is available from https://github.com/Labdoo/Labdoo-2.0.  

This document provides a description of the features implemented by the Labdoo social network.

* Feature Set

** The five basic objects

At its core, the Labdoo social network is based around five types of objects: labdooers, doojects, dootrips, edoovillages and hubs.

- Labdooers: Labdoo users.

- Doojects: Labdoo objects. The actual devices (objects) such as laptops, tablets, etc. that get loaded with education applications and transported to needy schools.

- Dootrips: Labdoo trips. CO2 neutral transportation means used to carry laptops from one location to another. Examples of dootrips are trips carried out by tourists, NGO volunteers (doctors and engineers without borders, humanitarian personnel, etc.), international students, employees of international corporations, etc.

- Edoovillages: Schools who receive doojects such as laptops or tablets loaded with education software.

- Hubs: while everyone can participate (from home, from school, from work, etc.), labdooers find commonly useful to organize themselves locally as groups of volunteers. A hub is just that, a group of labdooers located in a given region that get together to carry out Labdoo tasks.

** The main navigation menu

The main layout of the Labdoo system is controlled via the main navigation menu (MNM), located at the top of the page. The MNM is present in all the pages and allows users to quickly move to the various resources and tools. An important property of the MNM is that the availability of the various options depend on the role of the user. The more roles a user has, the more options he/she sees in the main navigation menu.

Given their relevance, users can find in the MNM access tabs to each of the five basic objects: doojects, dootrips, edoovillages, hubs and the user account tabs.

** Types of user roles

A user can have one of the following roles:

- Anonymous user: corresponds to users who visit labdoo.org without logging into an account. These users can only do “view” type of activities.

- Authenticated user: corresponds to the very basic labdoo user role. This is the role that a labdooer receives by default when registering for the first time to the system. This type of account allows users to perform all the base functions such as tagging laptops or registering a dootrip.

- Hub manager: provides additional functions to manage hubs.

- Edoovillage manager: provides additional functions to manage edoovillages.

- Newsletter manager: provides additional functions to manage, edit, and publish newsletters issues.

- Wiki writer: provides additional functions to write new wiki documents.

- Team manager: provides additional functions to manage Labdoo teams.

- Superhub manager: provides additional functions to create new hubs and help manage larger Labdoo regions englobing multiple hubs.

** Visualization dashboards

The design of the Labdoo social network puts special emphasis to providing transparency as one of the key mechanisms to facilitate the health of the system. To enable transparency, a series of dashboards are implemented that allow users to quickly know the status of the various objects (doojects, dootrips, hubs, edoovillages, etc). These dashboards rely on a variety of mechanisms including geolocation maps, column charts, or dynamically configurable tables, to name a few.

** Labdoo teams

Labdoo provides a framework to help labdooers manage their own projects and activities in collaboration with other labdooers. We call this feature "Labdoo teams". Each team organizes around a theme or topic, and users can join teams depending on their interests. Users with the "team manager" role can also create their own new teams and communities around them.

Inside a team, Labdoo users can perform the following tasks:

- Start a conversation.

- Create a task to be performed some time scheduled in the future.

- Create an event in a calendar (e.g., a typical example of event is a laptop sanitation event).

- View the wall of that team and engage in discussions.

- View the calendar of events in that team.

** Translations

To facilitate equal opportunities of access to the Labdoo resources, an important aspect of the platform is multi-language support. Labdoo has built-in technology to enable the rapid translation of its interface to a new language. An objective of the platform is to support as many languages as possible. For more information on how you can help translate Labdoo to your language, please read the document https://github.com/Labdoo/Labdoo-2.0/blob/master/translations/README.org.

** Activity feeds

So that all users (visitors, logged in users, participants, technology recipients, donors, etc.) can get a good sense of the activities carried out within the Labdoo network, the system provides various types of feeds. These feeds display both real time information of the activities being carried out as well as historical data of all past activities. Activity feeds can also be searched and filtered (for instance, you can specify to only display the activities carried out by you).

The main function of the activities feed is to help improve the transparency of the Labdoo system at all times to preserve the healthy state of the platform.

** Communications

TODO

** Global inventory checks (GICs)

TODO

** Photo albums

TODO

** Progress bars

TODO

** Downloading snapshots of work in progress

TODO

** REST API

TODO

** Tracking my contributions

TODO

** Outreaching using newsletters

TODO

** The Labdoo wiki

TODO

** FTP resources

TODO

** My account

TODO

** Superhub pages

TODO

** Signals

TODO

- Automatic emails

- On page signals (relations between users and objects)

- Cron type of signals


