<?php

/**
 * @defgroup labdoogics LabdooGics: Module implementing Labdoo's Global Inventory Checks (GICs) 
 *
 * This module implements the set of forms and subroutines needed for managing Global Inventory Checks (GICs) 
 *
 */


/**
 * @file
 * Main module file for the Labdoo GICs module 
 *
 * @ingroup labdoogics
 *
 */


/**
 * Generate the possible status values a GIC entry can have. 
 *
 * @param array $statusKeys An array mapping integer indexes to status keys 
 * @param array $statusValues An array mapping integer indexes to status values 
 *
 */
function generate_gic_status_values(&$statusKeys, &$statusValues) {
  $allowedValues = list_allowed_values(field_info_field("field_status"));
  $index = 0;
  foreach($allowedValues as $key => $statusValue) {
    $statusValues[$index] = $statusValue;
    $statusKeys[$index] = $key;
    $index++;
  }
  return;
}


/**
 *
 * gic_table - Defines the GIC table form
 *
 */
function gic_table($form, &$form_state, $edoovillageId) {
  global $user;
  global $language;
  $form = array();
  $cantSubmit = TRUE;
  $gicIsEmpty = TRUE;
  $statusKeys = array();
  $statusValues = array();
  generate_gic_status_values($statusKeys, $statusValues);

  $defaultLanguage = language_default();
  if($language->language != $defaultLanguage->language)
    $langCode = "/" . $language->language;
  else
    $langCode = "";

  //
  // Do some sanity checks first
  //
  if(!is_numeric($edoovillageId))
    return $form;
  $loadedNode = node_load($edoovillageId);
  if($loadedNode == FALSE)
    return $form;
  if($loadedNode->type != "edoovillage")
    return $form;

  //
  // Check if the user has the right to submit this GIC
  //
  $userRoles = array_values($user->roles);
  if (in_array('administrator', $userRoles) || 
      in_array('edoovillage manager', $userRoles) ||
      in_array('hub manager', $userRoles)) 
    $cantSubmit = FALSE;

  //
  // Build the GIC form
  //
  $query = 'SELECT nid FROM node where nid IN (SELECT entity_id FROM field_data_field_edoovillage_destination WHERE field_edoovillage_destination_target_id=:eid) ORDER BY title';
  $result = db_query($query, array(':eid' => $edoovillageId));

  if($result->rowCount() > 0)
    $gicIsEmpty = FALSE;

  if($gicIsEmpty == TRUE) {
    $form['container'] = array(
      '#type'             => 'fieldset',
      '#description'      => t('No doojects currently deployed in this project.')
    );
    return $form;
  }
  else {
    $form['container'] = array(
      '#type'             => 'fieldset',
    );
  }

  foreach($result as $dooject) {
    $doojectId = $dooject->nid;
    $query = 'SELECT field_status_value FROM field_data_field_status WHERE entity_id=:nid';
    $status = db_query($query, array(':nid' => $doojectId))->fetchField();

    $query = 'SELECT title FROM node WHERE nid=:nid';
    $title = db_query($query, array(':nid' => $doojectId))->fetchField();
    $currentIndex = array_search($status, $statusKeys);

    $form['container'][$doojectId] = array (
      '#type'      => 'select',
      '#disabled'  => $cantSubmit,
      '#title'     => t('Dootronic <a href="@langCode/content/@id">@id</a>:', array('@langCode' => $langCode, '@id' => $title)),
      '#options'   => $statusValues,
      '#default_value'  => variable_get($doojectId, $currentIndex),
    );
  }

  $form['container']['submit'] = array (
    '#type'             => 'submit',
    '#disabled'         => $cantSubmit,
    '#value'            => t('Update GIC table'),
    '#executes_submit_callback' => TRUE,
  );

  //
  // Pass the edoovillage node ID as a parameter inside the form
  //
  $form['container']['edoovillageId'] = array(
    '#type' => 'value',
    '#value' => $edoovillageId 
  );

  return $form;
}


/**
 *
 * gic_table_submit - Defines the submit function of the GIC table form
 *
 */
function gic_table_submit($form, &$form_state) {
  global $user;
  $recordChanged = FALSE;
  $body = '<p><span style="color:#ff6600;"><strong>GIC Snapshot:</strong></span></p>';
  $edoovillageId=$form['container']['edoovillageId']['#value'];
  $statusKeys = array();
  $statusValues = array();
  generate_gic_status_values($statusKeys, $statusValues);

  $query = 'SELECT nid FROM node where nid IN (SELECT entity_id FROM field_data_field_edoovillage_destination WHERE field_edoovillage_destination_target_id=:eid) ORDER BY title';
  $result = db_query($query, array(':eid' => $edoovillageId));

  foreach($result as $dooject) {
    $doojectId = $dooject->nid;
    $newStatusKey = $statusKeys[$form['container'][$doojectId]['#value']];
    $query = 'SELECT field_status_value FROM field_data_field_status WHERE entity_id=:nid';
    $currentStatusKey = db_query($query, array(':nid' => $doojectId))->fetchField();

    $doojectNode = node_load($doojectId);
    $body = $body . 'Dootronic ID: <a href="../content/' . $doojectNode->title. '">' . $doojectNode->title . '</a> | Status: ' . $newStatusKey;

    if($newStatusKey != $currentStatusKey) {
      $recordChanged = TRUE;
      $body = $body . ' (record was changed from status ' . $currentStatusKey . ')';
      // TODO: this needs to be redone to support multilanguage
      $field_info = field_info_field("field_status");
      $langcode = $field_info['translatable'] ? $doojectNode->language : LANGUAGE_NONE;
      $doojectNode->field_status[$langcode][0]['value'] = $newStatusKey;
      node_save($doojectNode);
    }
    $body = $body . '<br>';

  }

  if($recordChanged) {
    $gicNode = new StdClass();
    $gicNode->type = 'gic';
    node_object_prepare($gicNode);
    $gicNode->title = 'GIC'; 
    $gicNode->language = LANGUAGE_NONE;
    $gicNode->body[LANGUAGE_NONE][0]['value']   = $body;
    $gicNode->body[LANGUAGE_NONE][0]['summary'] = '';
    $gicNode->body[LANGUAGE_NONE][0]['format']  = 'full_html';
    $gicNode->field_gic_edoovillage[LANGUAGE_NONE][0]['target_id'] = $edoovillageId;
    $gicNode->field_gic_date[LANGUAGE_NONE][0]['value'] = date("F j, Y, g:i a"); 
    $gicNode->created = time();
    $gicNode->changed = $gicNode->created;
    $gicNode->status = 1;
    $gicNode->promote = 0;
    $gicNode->sticky = 0;
    $gicNode->format = 2;
    $gicNode->uid = $user->uid;
    node_save($gicNode);
  }

  drupal_set_message(t('Your GIC table has been submitted successfully.'));
  $form_state['redirect'] = array('edoovillage', array('query' => array('e' => $edoovillageId)));

  return;
}

